version: '3.8'

services:

  auth_service1:
    build: ./auth_service
    depends_on:
      - db

  auth_service2:
    build: ./auth_service
    depends_on:
      - db

  event_service1:
    build: ./event_management_service
    depends_on:
      - db

  event_service2:
    build: ./event_management_service
    depends_on:
      - db

  user_service1:
    build: ./user_registration_service
    depends_on:
      - db

  user_service2:
    build: ./user_registration_service
    depends_on:
      - db

  load_balancer:
    build: ./load_balancer
    ports:
      - "8080:80"
    depends_on:
      - event_service1
      - event_service2
      - auth_service1
      - auth_service2
      - user_service1
      - user_service2

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scalable_assignment
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8084:80"

volumes:
  dbdata:
