version: '3.8'

services:

  auth_service:
    build: ./auth_service
    depends_on:
      - db
    deploy:
      replicas: 2

  event_service:
    build: ./event_management_service
    depends_on:
      - db
    deploy:
      replicas: 2

  user_service:
    build: ./user_registration_service
    depends_on:
      - db
    deploy:
      replicas: 2

  load_balancer:
    build: ./load_balancer
    ports:
      - "8080:80"
    depends_on:
      - event_service
      - auth_service
      - user_service

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scalable_assignment
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8084:80"

volumes:
  dbdata:
